version: "3.1"
services:
  neo:
    # this image is AGPLv3 licensed: https://www.graphfoundation.org/projects/ongdb/
    build: ./neo4j
    hostname: neo
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_AUTH=neo4j/pass
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_dbms_connector_http_listen__address=:7474

